language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
addons:
  code_climate:
    repo_token: bc5047e430fb6a0eca24136b16424ce6aafc56baa15a184b346a20d9e01c5668
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
services:
  - mongodb
