language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
addons:
  code_climate:
    repo_token: <token>
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
services:
  - mongodb
