language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
addons:
  code_climate:
    repo_token: 417e1d35a5453031b165d028842b4715691e2e88
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
services:
  - mongodb
